DATA_LOCATION = 'cleaning_filtering_modelisation/data'
DATA_FILENAME = 'data_filtered'
MODEL_LOCATION = 'cleaning_filtering_modelisation/models'
MODEL_FILENAME = 'model'
EXPLAINER_FILENAME = 'explainer'
